export const JOB_KNIGHT = 0;           // Apprentice Knight
export const JOB_WARRIOR = 1;          // Warrior
export const JOB_WIZARD = 2;           // Wizard
export const JOB_WEREWOLF = 3;         // Werewolf
export const JOB_PRIEST = 4;           // Priest
export const JOB_FALLEN_ANGEL = 5;     // Fallen Angel
export const JOB_ROGUE = 6;            // Thief
export const JOB_FIGHTER = 7;          // Martial Artist
export const JOB_MAGIC_LANCER = 8;     // Magic lancer
export const JOB_MAGIC_ARCHER = 9;     // Magic archer
export const JOB_BEAST_TAMER = 10;     // Beast Tamer
export const JOB_SUMMONER = 11;        // Summoner
export const JOB_PRINCESS = 12;        // Princess
export const JOB_MAGICAL_GIRL = 13;    // Magical Girl
export const JOB_NECROMANCER = 14;     // Necromancer
export const JOB_DEVIL = 15;           // Devil
export const JOB_SOUL_BRINGER = 16;    // Spiritist
export const JOB_CHAMPION = 17;        // Fighter
export const JOB_OPTICALIST = 18;      // Opticalist
export const JOB_BEAST_MAN = 19;       // Beast Man
export const PLAYER_JOB_COUNT = 20;